feat: add function for getting a list of attributes for customers
customerio/customerio-node pull request #158
Opened 2024-07-05 07:00 UTC by omBratteng

Adds a function for getting a list of customers attributes
https://customer.io/docs/api/app/#operation/getPeopleById

2024-07-05 10:16 UTC, rebelchris approved these changes

2024-07-05 11:32 UTC, nensidosari approved these changes

2026-05-08 12:31 UTC, mike-engel requested changes
Thanks for this PR, and sorry for the delay in review.

Another test should be added that tests against an empty array

2026-05-08 12:31 UTC, mike-engel commented on lib/api.ts
> +    if (isEmpty(ids)) {
`isEmpty` needs to be updated to handle arrays

2026-05-08 12:31 UTC, mike-engel commented on test/api.ts
> +test('#getAttributesBatch: fails without customerId', (t) => {
```suggestion
test('#getAttributesBatch: fails without customer ids', (t) => {
```

2026-05-08 12:31 UTC, mike-engel commented on test/api.ts
> +  t.truthy((t.context.client.request.post as SinonStub).calledWith(`${RegionUS.apiUrl}/customers/attributes`));
```suggestion
  t.true((t.context.client.request.post as SinonStub).calledWith(`${RegionUS.apiUrl}/customers/attributes`));
```

2026-05-08 12:31 UTC, mike-engel commented on test/api.ts
> +test('#getAttributesBatch: success with default type id', (t) => {
Another assertion is needed to make sure the ids were passed through correctly

2026-05-08 12:37 UTC, omBratteng commented
@mike-engel I no longer work at dailydev, so I do not have access to the fork and am unable to do the changes.

2026-05-08 12:37 UTC, closed without merging